projet/projet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taskmanager/', include('taskmanager.urls')),
]

projet/taskmanager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('projects', views.projects, name='projects'),
    path('project/<int:project_id>', views.project, name='project'),
    path('project/<int:project_id>/newtask', views.newtask, name='newtask'),
    path('task/<int:task_id>', views.task, name='task'),
    path('task/<int:task_id>/edittask', views.edittask, name='edittask'),
    path('connexion', views.connexion, name='connexion'),
    path('deconnexion', views.deconnexion, name='deconnexion'),
]

projet/taskmanager/models.py
from django.contrib.auth.models import User
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(User, related_name="projects")

    class Meta:
        verbose_name = "projet"

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "status"

    def __str__(self):
        return self.name


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    assignee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # A task may be temporarily without a assigned user, until a new one is assigned to it
    start_date = models.DateField()
    due_date = models.DateField()
    priority = models.PositiveIntegerField()
    status = models.ForeignKey(Status, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "task"

    def __str__(self):
        return self.name


class Journal(models.Model):
    date = models.DateTimeField()
    entry = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # Deleting the author shall not erase its message
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "journal"

    def __str__(self):
        return self.entry

projet/taskmanager/forms.py
from django import forms
from .models import Task


class ConnexionForm(forms.Form):  # used in login
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)


class ChatForm(forms.Form):  # used in the journal
    entry = forms.CharField(label="New entry")


class TaskForm(forms.ModelForm):  # based on the model Form; used in newtask and edittask
    class Meta:
        model = Task
        exclude = ('project',)  # the project will be the one the user is adding the project to (or the one that exists already)

projet/taskmanager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ConnexionForm, ChatForm, TaskForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .models import Project, Task, Journal
from django.utils import timezone


@login_required
def projects(request):
    # Home page that shows all the projects of the connected user
    user_projects = request.user.projects.all()  # Nous sélectionnons tous nos projets du utilisateur
    return render(request, 'taskmanager/projects.html', locals())


@login_required
def project(request, project_id):
    # Page that shows all the tasks of the selected project
    selected_project = get_object_or_404(Project, id=project_id)
    return render(request, 'taskmanager/project.html', locals())


@login_required
def task(request, task_id):
    # Page that shows task descriptions and its journal
    selected_task = get_object_or_404(Task, id=task_id)
    form = ChatForm(request.POST or None)
    if form.is_valid():
        entry = form.cleaned_data['entry']
        Journal(date=timezone.now(), entry=entry, author=request.user, task=selected_task).save()
    entries = Journal.objects.filter(task=selected_task)
    return render(request, 'taskmanager/task.html', locals())


@login_required
def newtask(request, project_id):
    # Page used to create a new task
    form = TaskForm(request.POST or None)
    selected_project = Project.objects.get(id=project_id)
    form.fields["assignee"].queryset = selected_project.members.all()  # only accepts the members involved in the project
    if form.is_valid():
        task_to_add = form.save(commit=False)
        task_to_add.project = Project.objects.get(id=project_id)
        task_to_add.save()
        return redirect('task', task_id=task_to_add.id)
    return render(request, 'taskmanager/newtask.html', locals())


@login_required
def edittask(request, task_id):
    # Page used to edit a already existing task
    selected_task = Task.objects.get(id=task_id)
    form = TaskForm(request.POST or None, instance=selected_task)
    form.fields["assignee"].queryset = Task.objects.get(id=task_id).project.members.all()  # only accepts the members involved in the project
    if form.is_valid():
        form.save()
        return redirect('task', task_id=task_id)
    return render(request, 'taskmanager/newtask.html', locals())  # We use the same template used to create a new task


def connexion(request):
    # login page (manually implemented)
    error = False
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
                return redirect(projects)
            else:  # sinon une erreur sera affichée
                error = True
    else:
        form = ConnexionForm()
    return render(request, 'taskmanager/connexion.html', locals())


def deconnexion(request):
    # Logout view that has no template, instead it redirects to the login page
    logout(request)
    return redirect(reverse(connexion))

projet/taskmanager/templates/taskmanager/connexion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Manage-me</h1>
    <h2>Manage your projects and tasks</h2><br/>
    <h3>Se connecter</h3>

    {% if error %}
    <p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
    {% endif %}

    {% if user.is_authenticated %} {# if the user tries to access the connexion page but is already connected #}
        Vous êtes connecté, {{ user.username }} ! <a href="{% url 'projects'%}"> Accueil </a>
    {% else %}
        <form action="{% url 'connexion' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Se connecter" />
        </form>
    {% endif %}
</body>
</html>

projet/taskmanager/templates/taskmanager/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Header</title>
    <style>
        th, td {
            border: 1px solid black;
            border-collapse: collapse;
            padding: 3px;
        }
        table {
            border: 1px solid black;
            border-collapse: collapse;
            width: 100%;
        }
    </style> {# table style common to all pages #}
</head>
<body>
{# header common to all pages #}
    <h1>Manage-me</h1>
    <h2>Manage your projects and tasks</h2>
    <h3> Welcome {{request.user}}   (Not you? <a href="{% url 'deconnexion' %}">Disconnect</a>)</h3><br/>
    {% block navigation %}{% endblock %}
    {% block main %}{% endblock %}
</body>
</html>

projet/taskmanager/templates/taskmanager/newtask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{# this template is used both for a new or a edited task #}

{% extends "taskmanager/header.html" %}
{% block navigation %}
    <div>

        <a href="{% url 'projects' %}">Projets</a>
        {# separation to use the proper variables according to the utilisation or this template (adding or editing a new task) #}
        {% if selected_task %}
            / <a href="{% url 'project' project_id=selected_task.project.id%}">{{ selected_task.project.name }}</a>
            / <a href="{% url 'task' task_id=selected_task.id%}">{{selected_task.name}}</a>
        {% else %}
            / <a href="{% url 'project' project_id=selected_project.id%}">{{selected_project.name}}</a>
        {% endif %}
    </div>
{% endblock %}
{% block main %}
    <form method="post"> {# action not informed because can either go to newtask or edittask, so it goes to whichone called this template #}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock%}}
</body>
</html>

projet/taskmanager/templates/taskmanager/project.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "taskmanager/header.html" %}
{% block navigation %}
<div>
    <a href="{% url 'projects' %}">Projets</a>
    / <a href="{% url 'project' project_id=selected_project.id%}">{{ selected_project.name }}</a>
</div>
{% endblock %}

{% block main %}
<h2>{{ selected_project.name }}</h2>

<h3><a href="{% url 'newtask' project_id=selected_project.id %}">Create a task</a> </h3>

<table>
    <tr>
        <th>Task</th>
        <th>Assignee</th>
        <th>Start date</th>
        <th>Due date</th>
    </tr>
    {% for task in selected_project.task_set.all %}
        <tr>
            <td><a href="{% url 'task' task_id=task.id %}">{{ task.name }}</a></td>
            <td>{{task.assignee}}</td>
            <td>{{task.start_date}}</td>
            <td>{{task.due_date}}</td>
            <td><a href="{% url 'edittask' task_id=task.id %}">Modifier cette tâche</a></td>
        </tr>
    {% empty %}
        <tr><td>Aucune tache.</td></tr>
    {% endfor %}
</table>
{% endblock %}
</body>
</html>

projet/taskmanager/templates/taskmanager/projects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "taskmanager/header.html" %}
{% block navigation %}
<div><a href="{% url 'projects' %}">Projets</a></div>
{% endblock %}

{% block main %}
<h2>Projets</h2>
<table>
    {% for project in user_projects %}
        <tr><td>
            <a href="{% url 'project' project_id=project.id %}">{{ project.name }}</a>
        </td></tr>
    {% empty %}
        <tr><td>Aucun projet.</td></tr>
    {% endfor %}
</table>

{% endblock %}
</body>
</html>

projet/taskmanager/templates/taskmanager/task.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "taskmanager/header.html" %}
{% block navigation %}
    <div>
        <a href="{% url 'projects' %}">Projets</a> /
        <a href="{% url 'project' project_id=selected_task.project.id%}">{{ selected_task.project.name }}</a> /
        <a href="{% url 'task' task_id=selected_task.id%}">{{selected_task.name}}</a>
    </div>
{% endblock %}

{% block main %}

    <h4><a href="{% url 'edittask' task_id=selected_task.id %}">Modifier cette tâche</a> </h4>
    <h2>{{ selected_task.project.name }}</h2>
    <h3>{{selected_task.name}}</h3>

    <p>{{ selected_task.description }}</p>

    <table>
        <tr><th>Assignee</th><td>{{selected_task.assignee}}</td></tr>
        <tr><th>Start date</th><td>{{selected_task.start_date}}</td></tr>
        <tr><th>Due date</th><td>{{selected_task.due_date}}</td></tr>
        <tr><th>Priority level</th><td>{{selected_task.priority}}</td></tr>
        <tr><th>Status</th><td>{{selected_task.status}}</td></tr>
    </table>

    <h4>History</h4>
    {% for journal in entries %}
        <div>
            {{journal.author}} ({{ journal.date }}): {{journal.entry}}
        </div>
    {% empty %}
        <p>Aucun journal.</p>
    {% endfor %}

{# form used to submit a new entry in the journal #}
    <form action="{% url 'task' task_id=selected_task.id%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock %}
</body>
</html>